import React from 'react';
import {PageHeader, PageContent} from './PageContainer/Page.jsx';
import {Panel} from './TextInput/TextInput.jsx';

let SingleURL = React.createClass({

  getInitialState: function(){
    return { id: -1,
             original: '',
             alias: '',
             title: 'URL'};
  },

  loadURLFromServer: function() {
    var server_url= (this.props.route.url+
      this.props.routeParams.urlId+
      '/'+this.props.location.search);
    console.log(server_url)
    $.ajax({
      url: server_url,
      dataType: 'json',
      success: function(data) {
        var alias='';
        var title='';
        if(data.alias){
          alias = this.props.route.alias_prefix+data.alias;
          title = 'Personalized URL';
        }else{
          alias = this.props.route.short_prefix+data.short;
          title = 'Short URL generated by app';
        }

        this.setState({
          id: data._id,
          original: data.original,
          alias: alias,
          title: title});
      }.bind(this),

      error: function(xhr, status, err) {
        alert(err.toString());
      }.bind(this)
    });
  },

  componentDidMount: function(){
    this.loadURLFromServer();
  },

  render: function() {
    return (
      <div>
        <PageHeader>
          <i>{this.state.id}</i>
        </PageHeader>
        <PageContent>
          <div className="col-lg-8">
            <div className="bs-component">
              <Panel panel_type="info" panel_title="Original URL" >
                <p>{this.state.original}</p>
              </Panel>
              <Panel panel_type="info" panel_title={this.state.title} >
                <a href={this.state.alias} target="_blank">{this.state.alias}</a>
              </Panel>
            </div>
          </div>
        </PageContent>
      </div>
    )
  }
});

export default SingleURL;
